### PR TITLE
B01 Regional Implementation

### PR DESCRIPTION
**Pull request by julianKD**
Hello Marc,

This pull requests contains adjustements to consider the local regional windows settings for the "Workbook.SaveAs" function and the "csv.DictReader" list separator.

It also gives user feedback whenever a date with a US format (mm/dd/yyyy) is not interpretable (e.g. 31/02/2022 - dd/mm/yyyy)

Please review by file

Would be nice if you could accept this, it should not affect the core functionality of the extension.

Thank you,
Best,
Julian

### CODE REVIEW

**Comment by julianKD** [comment]
Comment on changes in the VB script:

file:
[lib/drawinglistsync/xls2csv.vbs](https://github.com/revitron/revitron-drawing-list-sync/pull/1/files#diff-6473996450ca872e7aa956a2efc0ea3af538cf9a6c997e08886b3f7de48f3903)

> `True
 saves files against the language of Microsoft Excel (including control panel settings). False
 (default) saves files against the language of Visual Basic for 
Applications (VBA) (which is typically US English unless the VBA project
 where Workbooks.Open
 is run from is an old internationalized XL5/95 VBA project).`

https://learn.microsoft.com/de-de/office/vba/api/excel.workbook.saveas

**Comment by marcantondahmen** [comment]
Hi, maybe I don't understand the purpose of this changes correctly, but why is it not just enough to simply extend the date regex and add one more format to the date format list? And I guess as long as all possible formats are added, the actual language that is used to create the `.csv` files doesn't matter anymore.

**Comment by julianKD** [comment]
Hi Marc,

I understand what you mean. This was something I thought about but in the end I was not satisfied with it. The reason is, that the VB process that opens and saves the Excel file is not transparent for me as a developer or the user. I can not see how it interprets different date settings from the original excel file. 

When I open the content that is temporarily created, I can only see two things: the Excel file from the temp folder that shows the content in my regional language settings, and the csv file that shows a comma-separated version with dates that have US format mm/dd/yyyy, and unfortunately sometimes dd/mm/yyyy.
This discrepancy might be caused by the date settings in the original Excel file, and requires a certain standard setup in the Excel file. 
As a user, one does not know what to set or how to get the right format because the result does not match what they see in Excel.

If I do not know if its dd/mm/yyyy or mm/dd/yyyy in the csv, I can not use a regex pattern anymore. For example, for 04.04.2023, regex is unable to determine which format it is.

For me that was not a satisfying process because it might cause errors that the user can not identify.
Maybe there is another way to fix that, but using the regional setting makes the process more tansparant in my opinion.
It might be an option to read the excel and the date formats directly from there.
What do you think?

Best,
Julian

**Comment by julianKD** [comment]
easier solution found by adjusting the date format in the excel file to the regional format (FormatDateTime(cell.Value, vbShortDate)

**Pull request closed without merging**
